spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3308/azhu
  #session过期时间：1天
  session:
    timeout: 86400
server:
  address: 0.0.0.0