spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3308/azhu
  #session过期时间：1天
  session:
    timeout: 86400
server:
  servlet:
    context-path: /api
  port: 8080
mybatis-plus:
  configuration:
    #驼峰
    map-underscore-to-camel-case: false
  type-aliases-package: com.example.usercenter.model
  #??mapper??
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)